### ISSUE TITLE
2 Requested Features

### ISSUE THREAD

**Issue by UserAccount123** [PatrickAlex2019/ApkEditor#11]
Please add these features:
1. Enable removing & blocking ads from any app then rebuilding it (+ removing ads space).
2. Enable making any app fully offline (blocking internet access).
Thanks.

**Comment by PatrickAlex2019** [comment]
Maintenance has been stopped.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: USER ***@***.***>
发送时间: Monday, September 9, 2024 7:14:25 PM
收件人: PatrickAlex2019/ApkEditor ***@***.***>
抄送: Subscribed ***@***.***>
主题: [PatrickAlex2019/ApkEditor] Feature Request (Issue #11)


Please add a tool to disable ads from any app then rebuilding it (+ removing ads space).
Thsnks.

―
