### ISSUE TITLE
Unsafe APK 

### ISSUE THREAD

**Issue by 10x7** [PatrickAlex2019/ApkEditor#12]
I had hope for this **application**, it looks **good** and **complete** for my needs until i realised it is **flagged** 9/10, even by people...

Yeah, most **AV** engine flagged this project/product, _well sad_, id hope for the future they would **remove** any **malicious** code or the ones that would **flag** it or just **_[rem]_**.
###### please??

**Comment by PatrickAlex2019** [comment]
The software does not have any reinforcement, and you can completely use MT manager or jadx to modify it twice. I have no plan to update it, so it has not been updated from 2022 to 2024

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: nom ***@***.***>
发送时间: Monday, November 4, 2024 7:20:42 PM
收件人: PatrickAlex2019/ApkEditor ***@***.***>
抄送: Subscribed ***@***.***>
主题: [PatrickAlex2019/ApkEditor] Unsafe APK (Issue #12)


I had hope for this application, it looks good and complete for my needs until i realised it is flagged 9/10, even by people...

Yeah, most AV engine flagged this project/product, well sad, id hope for the future they would remove any malicious code or the ones that would flag it or just [rem].

If you guys would please clarify and give us some answers?, maybe it will clear things up
please??

―

**Comment by 10x7** [comment]
I **actually** didn't expect you would **reply** from a project updated 2 years ago, I **appreciate** your response, i understand why you didn't updated it, but i **suggest** you add a disclaimer so that other people would understand the issues and the projects inactive, again thanks for the response ^_^
